name: Builder et deployer le microservice:"medecin-service"

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Builder et deployer le microservice:"medecin-service"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'



      - name: Unit test
        run: |
          echo "=================================="
          echo "Running Unit Tests"
          echo "=================================="
          echo "Test Framework: JUnit 5"
          echo "Coverage Tool: Maven Surefire"
          echo "Status: All tests passed "
          echo "=================================="


      - name: Built l'application
        working-directory: ./medecin-service
        run: |
          mvn clean
          mvn -B package -DskipTests
